language: node_js
node_js:
- 'lts/*'
before_script:
- npm install -g grunt-cli
script: grunt test
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: hK/pYShzH17XcfbHeIg2McqAEPKpVbiklYjD5EuJUe9MTAnBAPC2VmZwjMTziqJiOcLGn3eFqHP4nPXXi9vo54bVB2SHvJZ/OWaDWS70k+cx69cu8B2+87BMKonOcGOdmi9awvt9GaOBMm4cWVOIeiQicVqhmFIc233l8fTG86c=
  on:
    tags: true
    repo: noflo/grunt-noflo-browser
