language: node_js
node_js:
- lts/*
before_script:
- npm install -g grunt-cli
script: grunt test
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: UhGgIG0Rzu59agGfxGn92papWzR2DpqD252A5K4zoInfeWQitbv0zIPO/dldhQ6AMz5wTYnq0sgr5U9AcxlkhMcEQD34xAvfrJP5eCaXsVIoqtHMSQakTFzzi4a5kXoK63DklVqp4b1SNLwAtqX106tUjDAawmzCidwEDyzcBrI=
  on:
    tags: true
    repo: noflo/grunt-noflo-browser
